In [577]:
import pandas as pd

In [578]:
import matplotlib.pyplot as plt
import matplotlib

In [579]:
dados = pd.read_table("pes2013A.txt.gz", sep=" ", compression="gzip")

In [580]:
dados.rename(columns={"V8005":"IDADE"}, inplace=True)

In [581]:
dados.rename(columns={"UF":"ESTADO"}, inplace=True)

In [582]:
dados.rename(columns={"V6003":"CURSO"}, inplace=True)

In [583]:
dados.rename(columns={"V6002":"REDE"}, inplace=True)

In [584]:
dados.rename(columns={"V0404":"COR"}, inplace=True)

In [585]:
dados = dados.loc[:,("IDADE", "ESTADO","CURSO","REDE","COR")]

In [586]:
bins = list(range(0,120,12))

In [587]:
coluna_idades = pd.cut(importantes.IDADE, bins, include_lowest=True)

In [588]:
coluna_idades

1         (36, 48]
2         (60, 72]
3         (12, 24]
4         (12, 24]
5         (12, 24]
6         (12, 24]
7         (48, 60]
8         (48, 60]
9         (24, 36]
10        (12, 24]
11         [0, 12]
12        (36, 48]
13        (24, 36]
14         [0, 12]
15        (48, 60]
16        (12, 24]
17        (24, 36]
18        (36, 48]
19        (24, 36]
20        (12, 24]
21        (12, 24]
22         [0, 12]
23        (48, 60]
24        (36, 48]
25         [0, 12]
26        (24, 36]
27        (48, 60]
28         [0, 12]
29        (24, 36]
30        (48, 60]
            ...
362526     [0, 12]
362527    (24, 36]
362528    (36, 48]
362529     [0, 12]
362530     [0, 12]
362531     [0, 12]
362532    (36, 48]
362533    (36, 48]
362534    (12, 24]
362535    (12, 24]
362536    (12, 24]
362537    (12, 24]
362538    (12, 24]
362539    (48, 60]
362540    (36, 48]
362541    (12, 24]
362542    (12, 24]
362543    (24, 36]
362544    (48, 60]
362545    (12, 24]
362546    (48, 60]
362547    (36, 48]
362548     [0, 12]
362549    (12, 24]
362550    (24, 36]
362551    (24, 36]
362552     [0, 12]
362553     [0, 12]
362554    (24, 36]
362555     [0, 12]
Name: IDADE, dtype: category
Categories (9, object): [[0, 12], (12, 24], (24, 36], (36, 48], ..., (60, 72], (72, 84], (84, 96], (96, 108]]

In [589]:
dados["FAIXA_IDADES"] = coluna_idades

In [590]:
dados_ordenados = dados.sort(["FAIXA_IDADES", "IDADE"])

In [591]:
dados_ordenados = dados.sort(["FAIXA_IDADES", "IDADE"])

In [592]:
dados_ordenados.loc[:, ("FAIXA_IDADES", "IDADE")]

       FAIXA_IDADES  IDADE
169         [0, 12]      0
259         [0, 12]      0
283         [0, 12]      0
290         [0, 12]      0
324         [0, 12]      0
401         [0, 12]      0
455         [0, 12]      0
592         [0, 12]      0
645         [0, 12]      0
682         [0, 12]      0
769         [0, 12]      0
792         [0, 12]      0
807         [0, 12]      0
938         [0, 12]      0
1044        [0, 12]      0
1049        [0, 12]      0
1073        [0, 12]      0
1172        [0, 12]      0
1191        [0, 12]      0
1414        [0, 12]      0
1487        [0, 12]      0
1576        [0, 12]      0
1704        [0, 12]      0
1774        [0, 12]      0
1787        [0, 12]      0
1990        [0, 12]      0
2073        [0, 12]      0
2121        [0, 12]      0
2131        [0, 12]      0
2179        [0, 12]      0
...             ...    ...
247876    (96, 108]    101
251945    (96, 108]    101
254776    (96, 108]    101
311306    (96, 108]    101
98480     (96, 108]    102
124727    (96, 108]    102
164281    (96, 108]    102
181276    (96, 108]    102
188473    (96, 108]    102
356987    (96, 108]    102
50690     (96, 108]    103
63344     (96, 108]    103
63527     (96, 108]    103
66144     (96, 108]    103
98390     (96, 108]    103
100699    (96, 108]    103
118326    (96, 108]    103
135408    (96, 108]    103
145433    (96, 108]    103
271364    (96, 108]    103
36262     (96, 108]    104
176221    (96, 108]    104
313316    (96, 108]    104
22150     (96, 108]    105
77657     (96, 108]    105
147514    (96, 108]    105
228646    (96, 108]    105
109643    (96, 108]    106
234354    (96, 108]    107
30914           NaN    109

[362555 rows x 2 columns]

In [593]:
dados.ESTADO = dados.ESTADO.astype('category')

In [594]:
dados.ESTADO.cat.categories = ('Rondônia','Acre','Amazonas','Roraima','Pará','Amapá','Tocantins','Maranhão','Piauí','Ceará','Rio Grande do Norte','Paraíba','Pernambuco','Alagoas','Sergipe','Bahia','Minas Gerais','Espírito Santo','Rio de Janeiro','São Paulo','Paraná','Santa Catarina','Rio Grande do Sul','Mato Grosso do Sul','Mato Grosso','Goiás','Distrito Federal')

In [595]:
dados.REDE = dados.REDE.astype('category')

In [596]:
dados.REDE.cat.categories = ('Pública','Privada')

In [597]:
dados.COR = dados.COR.astype('category')

In [598]:
dados.COR.cat.categories = ('Indígena','Branca','Preta','Amarela','Parda','Sem declaração')

In [599]:
dados.CURSO = dados.CURSO.astype('category')

In [600]:
dados.CURSO.cat.categories = ('Regular do ensino fundamental','Regular do ensino médio','Educação de jovens e adultos ou supletivo do ensino fundamental','Educação de jovens e adultos ou supletivo do ensino médio','Superior de graduação','Alfabetização de jovens e adultos','Creche','Classe de alfabetização - CA', 'Maternal, jardim de infância etc.','Pré-vestibular','Mestrado ou doutorado')

In [601]:
candidatos = dados[(dados.CURSO=='Regular do ensino médio')|(dados.CURSO=='Educação de jovens e adultos ou supletivo do ensino médio')|(dados.CURSO=='Pré-vestibular')]

In [602]:
dados

,IDADE,ESTADO,CURSO,REDE,COR,FAIXA_IDADES
1,42,Rondônia,NaN,NaN,Branca,"(36, 48]"
2,64,Rondônia,NaN,NaN,Parda,"(60, 72]"
3,13,Rondônia,Regular do ensino fundamental,Pública,Preta,"(12, 24]"
4,23,Rondônia,NaN,NaN,Parda,"(12, 24]"
5,19,Rondônia,Superior de graduação,Privada,Parda,"(12, 24]"
6,17,Rondônia,Regular do ensino médio,Privada,Parda,"(12, 24]"
7,59,Rondônia,NaN,NaN,Preta,"(48, 60]"
8,56,Rondônia,NaN,NaN,Branca,"(48, 60]"
9,25,Rondônia,NaN,NaN,Parda,"(24, 36]"
10,23,Rondônia,NaN,NaN,Branca,"(12, 24]"
11,5,Rondônia,"Maternal, jardim de infância etc.",Pública,Branca,"[0, 12]"
12,37,Rondônia,NaN,NaN,Branca,"(36, 48]"
13,25,Rondônia,NaN,NaN,Branca,"(24, 36]"
14,4,Rondônia,Creche,Privada,Branca,"[0, 12]"
15,50,Rondônia,NaN,NaN,Branca,"(48, 60]"
16,23,Rondônia,Superior de graduação,Privada,Branca,"(12, 24]"
17,28,Rondônia,NaN,NaN,Branca,"(24, 36]"
18,41,Rondônia,NaN,NaN,Branca,"(36, 48]"
19,34,Rondônia,NaN,NaN,Branca,"(24, 36]"
20,17,Rondônia,Regular do ensino médio,Pública,Branca,"(12, 24]"
21,15,Rondônia,Regular do ensino médio,Pública,Branca,"(12, 24]"
22,1,Rondônia,NaN,NaN,Branca,"[0, 12]"
23,51,Rondônia,NaN,NaN,Parda,"(48, 60]"
24,44,Rondônia,NaN,NaN,Preta,"(36, 48]"
25,8,Rondônia,Regular do ensino fundamental,Pública,Preta,"[0, 12]"
26,36,Rondônia,NaN,NaN,Branca,"(24, 36]"
27,49,Rondônia,NaN,NaN,Branca,"(48, 60]"
28,9,Rondônia,Regular do ensino fundamental,Pública,Parda,"[0, 12]"
29,25,Rondônia,NaN,NaN,Branca,"(24, 36]"
30,57,Rondônia,NaN,NaN,Parda,"(48, 60]"
...,...,...,...,...,...,...
362526,10,Distrito Federal,Regular do ensino fundamental,Pública,Preta,"[0, 12]"
362527,33,Distrito Federal,NaN,NaN,Branca,"(24, 36]"
362528,43,Distrito Federal,NaN,NaN,Branca,"(36, 48]"
362529,12,Distrito Federal,Regular do ensino fundamental,Pública,Branca,"[0, 12]"
362530,9,Distrito Federal,Regular do ensino fundamental,Pública,Branca,"[0, 12]"
362531,7,Distrito Federal,Regular do ensino fundamental,Pública,Branca,"[0, 12]"
362532,42,Distrito Federal,NaN,NaN,Parda,"(36, 48]"
362533,38,Distrito Federal,NaN,NaN,Parda,"(36, 48]"
362534,18,Distrito Federal,NaN,NaN,Parda,"(12, 24]"
362535,15,Distrito Federal,Regular do ensino médio,Pública,Parda,"(12, 24]"
362536,14,Distrito Federal,Regular do ensino fundamental,Pública,Parda,"(12, 24]"
362537,18,Distrito Federal,Regular do ensino médio,Pública,Parda,"(12, 24]"
362538,23,Distrito Federal,NaN,NaN,Parda,"(12, 24]"
362539,50,Distrito Federal,NaN,NaN,Branca,"(48, 60]"
362540,39,Distrito Federal,NaN,NaN,Branca,"(36, 48]"
362541,21,Distrito Federal,NaN,NaN,Branca,"(12, 24]"
362542,22,Distrito Federal,Superior de graduação,Privada,Parda,"(12, 24]"
362543,35,Distrito Federal,NaN,NaN,Branca,"(24, 36]"
362544,49,Distrito Federal,NaN,NaN,Branca,"(48, 60]"
362545,13,Distrito Federal,Regular do ensino fundamental,Pública,Branca,"(12, 24]"
362546,54,Distrito Federal,NaN,NaN,Branca,"(48, 60]"
362547,48,Distrito Federal,NaN,NaN,Parda,"(36, 48]"
362548,5,Distrito Federal,"Maternal, jardim de infância etc.",Pública,Parda,"[0, 12]"
362549,17,Distrito Federal,Regular do ensino médio,Pública,Preta,"(12, 24]"
362550,30,Distrito Federal,Superior de graduação,Privada,Branca,"(24, 36]"
362551,33,Distrito Federal,NaN,NaN,Preta,"(24, 36]"
362552,11,Distrito Federal,Regular do ensino fundamental,Pública,Branca,"[0, 12]"
362553,2,Distrito Federal,NaN,NaN,Parda,"[0, 12]"
362554,32,Distrito Federal,NaN,NaN,Parda,"(24, 36]"
362555,6,Distrito Federal,Regular do ensino fundamental,Pública,Parda,"[0, 12]"

In [603]:
candidatos = candidatos.sort(["CURSO"])
candidatos

,IDADE,ESTADO,CURSO,REDE,COR,FAIXA_IDADES
6,17,Rondônia,Regular do ensino médio,Privada,Parda,"(12, 24]"
230077,17,São Paulo,Regular do ensino médio,Pública,Parda,"(12, 24]"
230131,15,São Paulo,Regular do ensino médio,Pública,Parda,"(12, 24]"
230146,15,São Paulo,Regular do ensino médio,Pública,Parda,"(12, 24]"
230167,16,São Paulo,Regular do ensino médio,Pública,Branca,"(12, 24]"
230173,15,São Paulo,Regular do ensino médio,Pública,Branca,"(12, 24]"
230186,16,São Paulo,Regular do ensino médio,Pública,Branca,"(12, 24]"
230189,15,São Paulo,Regular do ensino médio,Pública,Parda,"(12, 24]"
230193,15,São Paulo,Regular do ensino médio,Pública,Parda,"(12, 24]"
230208,15,São Paulo,Regular do ensino médio,Pública,Parda,"(12, 24]"
230228,16,São Paulo,Regular do ensino médio,Privada,Branca,"(12, 24]"
230302,17,São Paulo,Regular do ensino médio,Pública,Branca,"(12, 24]"
230306,17,São Paulo,Regular do ensino médio,Pública,Branca,"(12, 24]"
230307,15,São Paulo,Regular do ensino médio,Pública,Branca,"(12, 24]"
229996,16,São Paulo,Regular do ensino médio,Pública,Parda,"(12, 24]"
230357,16,São Paulo,Regular do ensino médio,Pública,Preta,"(12, 24]"
230384,17,São Paulo,Regular do ensino médio,Pública,Branca,"(12, 24]"
230394,15,São Paulo,Regular do ensino médio,Privada,Branca,"(12, 24]"
230461,18,São Paulo,Regular do ensino médio,Pública,Branca,"(12, 24]"
230552,16,São Paulo,Regular do ensino médio,Pública,Branca,"(12, 24]"
230553,14,São Paulo,Regular do ensino médio,Pública,Branca,"(12, 24]"
230556,17,São Paulo,Regular do ensino médio,Pública,Branca,"(12, 24]"
230596,16,São Paulo,Regular do ensino médio,Pública,Parda,"(12, 24]"
230603,32,São Paulo,Regular do ensino médio,Pública,Branca,"(24, 36]"
230637,16,São Paulo,Regular do ensino médio,Pública,Branca,"(12, 24]"
230719,14,São Paulo,Regular do ensino médio,Pública,Branca,"(12, 24]"
230736,18,São Paulo,Regular do ensino médio,Pública,Branca,"(12, 24]"
230737,16,São Paulo,Regular do ensino médio,Pública,Branca,"(12, 24]"
230782,15,São Paulo,Regular do ensino médio,Pública,Parda,"(12, 24]"
230373,15,São Paulo,Regular do ensino médio,Pública,Preta,"(12, 24]"
...,...,...,...,...,...,...
265950,20,São Paulo,Pré-vestibular,Privada,Branca,"(12, 24]"
291244,18,Santa Catarina,Pré-vestibular,Privada,Branca,"(12, 24]"
33920,18,Pará,Pré-vestibular,Privada,Preta,"(12, 24]"
170150,22,Minas Gerais,Pré-vestibular,Privada,Parda,"(12, 24]"
154694,20,Bahia,Pré-vestibular,Privada,Preta,"(12, 24]"
142235,18,Bahia,Pré-vestibular,Privada,Parda,"(12, 24]"
253269,18,São Paulo,Pré-vestibular,Privada,Branca,"(12, 24]"
253302,22,São Paulo,Pré-vestibular,Privada,Branca,"(12, 24]"
33716,35,Pará,Pré-vestibular,Privada,Parda,"(24, 36]"
170205,21,Minas Gerais,Pré-vestibular,Privada,Branca,"(12, 24]"
276245,18,Paraná,Pré-vestibular,Privada,Branca,"(12, 24]"
251713,21,São Paulo,Pré-vestibular,Privada,Branca,"(12, 24]"
312888,25,Rio Grande do Sul,Pré-vestibular,Privada,Branca,"(24, 36]"
253425,18,São Paulo,Pré-vestibular,Privada,Branca,"(12, 24]"
222368,30,Rio de Janeiro,Pré-vestibular,Privada,Branca,"(24, 36]"
191274,29,Minas Gerais,Pré-vestibular,Privada,Parda,"(24, 36]"
311273,23,Rio Grande do Sul,Pré-vestibular,Privada,Parda,"(12, 24]"
143363,33,Bahia,Pré-vestibular,Privada,Parda,"(24, 36]"
143335,20,Bahia,Pré-vestibular,Privada,Preta,"(12, 24]"
280662,19,Paraná,Pré-vestibular,Privada,Branca,"(12, 24]"
337632,17,Mato Grosso,Pré-vestibular,Privada,Branca,"(12, 24]"
280654,18,Paraná,Pré-vestibular,Privada,Branca,"(12, 24]"
280598,19,Paraná,Pré-vestibular,Privada,Branca,"(12, 24]"
198550,18,Espírito Santo,Pré-vestibular,Pública,Branca,"(12, 24]"
198915,17,Espírito Santo,Pré-vestibular,Privada,Parda,"(12, 24]"
336856,25,Mato Grosso,Pré-vestibular,Privada,Parda,"(24, 36]"
253452,20,São Paulo,Pré-vestibular,Privada,Branca,"(12, 24]"
276222,18,Paraná,Pré-vestibular,Privada,Branca,"(12, 24]"
143092,18,Bahia,Pré-vestibular,Pública,Parda,"(12, 24]"
37439,35,Pará,Pré-vestibular,Privada,Branca,"(24, 36]"

In [604]:
local_candidatos =  pd.crosstab(candidatos.CURSO, candidatos.ESTADO)

In [605]:
local_candidatos.sum()

ESTADO
Rondônia                373
Acre                    241
Amazonas                738
Roraima                 150
Pará                   1245
Amapá                   169
Tocantins               400
Maranhão                553
Piauí                   279
Ceará                   949
Rio Grande do Norte     216
Paraíba                 258
Pernambuco              997
Alagoas                 226
Sergipe                 283
Bahia                  1296
Minas Gerais           1597
Espírito Santo          275
Rio de Janeiro         1108
São Paulo              1801
Paraná                  869
Santa Catarina          438
Rio Grande do Sul      1125
Mato Grosso do Sul      247
Mato Grosso             413
Goiás                   715
Distrito Federal        442
dtype: int64

In [606]:
perfil_candidatos = pd.crosstab(candidatos.COR, candidatos.REDE)
perfil_candidatos

REDE            Pública  Privada
COR
Indígena             65        4
Branca             5486     1485
Preta              1201      105
Amarela              48       23
Parda              8173      813
Sem declaração        0        0

In [607]:
pd.DataFrame.plot(kind='bar', data=pd.crosstab(candidatos.REDE, candidatos.COR), color=('green', 'salmon', 'black', 'yellow', 'brown'), stacked=True)

In [608]:
idade_candidatos = candidatos.loc[:,("CURSO", "FAIXA_IDADES")]
idade_candidatos

                          CURSO FAIXA_IDADES
6       Regular do ensino médio     (12, 24]
230077  Regular do ensino médio     (12, 24]
230131  Regular do ensino médio     (12, 24]
230146  Regular do ensino médio     (12, 24]
230167  Regular do ensino médio     (12, 24]
230173  Regular do ensino médio     (12, 24]
230186  Regular do ensino médio     (12, 24]
230189  Regular do ensino médio     (12, 24]
230193  Regular do ensino médio     (12, 24]
230208  Regular do ensino médio     (12, 24]
230228  Regular do ensino médio     (12, 24]
230302  Regular do ensino médio     (12, 24]
230306  Regular do ensino médio     (12, 24]
230307  Regular do ensino médio     (12, 24]
229996  Regular do ensino médio     (12, 24]
230357  Regular do ensino médio     (12, 24]
230384  Regular do ensino médio     (12, 24]
230394  Regular do ensino médio     (12, 24]
230461  Regular do ensino médio     (12, 24]
230552  Regular do ensino médio     (12, 24]
230553  Regular do ensino médio     (12, 24]
230556  Regular do ensino médio     (12, 24]
230596  Regular do ensino médio     (12, 24]
230603  Regular do ensino médio     (24, 36]
230637  Regular do ensino médio     (12, 24]
230719  Regular do ensino médio     (12, 24]
230736  Regular do ensino médio     (12, 24]
230737  Regular do ensino médio     (12, 24]
230782  Regular do ensino médio     (12, 24]
230373  Regular do ensino médio     (12, 24]
...                         ...          ...
265950           Pré-vestibular     (12, 24]
291244           Pré-vestibular     (12, 24]
33920            Pré-vestibular     (12, 24]
170150           Pré-vestibular     (12, 24]
154694           Pré-vestibular     (12, 24]
142235           Pré-vestibular     (12, 24]
253269           Pré-vestibular     (12, 24]
253302           Pré-vestibular     (12, 24]
33716            Pré-vestibular     (24, 36]
170205           Pré-vestibular     (12, 24]
276245           Pré-vestibular     (12, 24]
251713           Pré-vestibular     (12, 24]
312888           Pré-vestibular     (24, 36]
253425           Pré-vestibular     (12, 24]
222368           Pré-vestibular     (24, 36]
191274           Pré-vestibular     (24, 36]
311273           Pré-vestibular     (12, 24]
143363           Pré-vestibular     (24, 36]
143335           Pré-vestibular     (12, 24]
280662           Pré-vestibular     (12, 24]
337632           Pré-vestibular     (12, 24]
280654           Pré-vestibular     (12, 24]
280598           Pré-vestibular     (12, 24]
198550           Pré-vestibular     (12, 24]
198915           Pré-vestibular     (12, 24]
336856           Pré-vestibular     (24, 36]
253452           Pré-vestibular     (12, 24]
276222           Pré-vestibular     (12, 24]
143092           Pré-vestibular     (12, 24]
37439            Pré-vestibular     (24, 36]

[17403 rows x 2 columns]

In [609]:
idade_candidatos2 = pd.crosstab(idade_candidatos.CURSO, candidatos.FAIXA_IDADES)
idade_candidatos2

FAIXA_IDADES,"[0, 12]","(12, 24]","(24, 36]","(36, 48]","(48, 60]","(60, 72]","(72, 84]","(84, 96]","(96, 108]"
CURSO,,,,,,,,,
Regular do ensino fundamental,0,0,0,0,0,0,0,0,0
Regular do ensino médio,0,15410,535,180,50,7,0,0,0
Educação de jovens e adultos ou supletivo do ensino fundamental,0,0,0,0,0,0,0,0,0
Educação de jovens e adultos ou supletivo do ensino médio,0,401,322,192,64,17,1,0,0
Superior de graduação,0,0,0,0,0,0,0,0,0
Alfabetização de jovens e adultos,0,0,0,0,0,0,0,0,0
Creche,0,0,0,0,0,0,0,0,0
Classe de alfabetização - CA,0,0,0,0,0,0,0,0,0
"Maternal, jardim de infância etc.",0,0,0,0,0,0,0,0,0
Pré-vestibular,0,180,31,10,2,1,0,0,0
Mestrado ou doutorado,0,0,0,0,0,0,0,0,0

In [613]:
idade_candidatos.FAIXA_IDADES
idade_candidatos.FAIXA_IDADES.value_counts(True)*100

(12, 24]     91.886456
(24, 36]      5.102569
(36, 48]      2.195024
(48, 60]      0.666552
(60, 72]      0.143653
(72, 84]      0.005746
(96, 108]     0.000000
(84, 96]      0.000000
[0, 12]       0.000000
dtype: float64

In [614]:
pd.DataFrame.plot(kind='pie', data=idade_candidatos.FAIXA_IDADES.value_counts(), colors=('yellow', 'salmon', 'blue', 'red', 'green'), autopct="%.2f", legend=False)